f1=open("output.txt","w")
f_write=f1.write('Hello,Python!')
f1.close()
f1=open("output.txt","r")
f_read=f1.read()
print("\nEnter text to write to the file:",f_read)
print("Data successfully written to output.txt")
f1.close()
f1=open("output.txt","w")
f_write2=f1.write('\nHello,Python!')
f1.close()
f1 = open("output.txt", 'a')
f_read2 = f1.write('\nLearning file handling in python')
print("\nEnter additional text to append:Learning file handling in python")
print("Data successfully appended")
f1.close()
f1=open("output.txt","r")
read=f1.read()
print("\nFinal content of output.txt:",read)
f1.close()